name: ${project.name}
version: ${project.version}
api: ["1.0.8"]
author: Scallop
description: ${project.description}
main: cn.yescallop.essentialsnk.EssentialsNK

permissions:
  essentialsnk.clearinventory:
    default: op
  essentialsnk.clearinventory.others:
    default: op
  essentialsnk.fly:
    default: op
  essentialsnk.fly.others:
    default: op
  essentialsnk.repair:
    default: op
  essentialsnk.repair.all:
    default: op
  essentialsnk.vanish:
    default: op
  essentialsnk.vanish.others:
    default: op
  essentialsnk.whois:
    default: op
  essentialsnk.whois.other:
    default: op
